name: Build and Upload JAR

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'build.gradle'
      - '.github/workflows/main.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - 'src/**'
      - 'build.gradle'
      - '.github/workflows/main.yml'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  DO_NOT_TRACK: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Verify Gradle installation
        run: ./gradlew --version

      - name: List initial directory contents
        run: ls -R

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build shadowJar

      - name: List build directory contents
        run: ls -R build

      - name: Create staging directory
        run: mkdir -p staging

      - name: Copy JAR to staging
        run: cp build/libs/*.jar staging/

      - name: List staging directory contents
        run: ls -R staging

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wherobots-jdbc-driver
          path: staging/*.jar
